name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  actions: "write"
  contents: "read"

env:
  RUNTIME_VERSION: 17
  GRADLE_WARNING_MODE: 'fail'

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "setup environment"
        id: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-java-env@trunk"
        with:
          runtime_version: "${{ env.RUNTIME_VERSION }}"
          gradle_warning_mode: "${{ env.GRADLE_WARNING_MODE }}"
      - name: "run gradle build"
        run: "./gradlew build"
